<a href="https://colab.research.google.com/github/Sylvanzsy/AIDataRepo/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
print(tensor)


tensor([[0.3551, 0.0738, 0.5534, 0.2092, 0.0706, 0.0835, 0.6496],
        [0.6240, 0.0099, 0.8213, 0.0029, 0.5059, 0.1305, 0.8088],
        [0.7047, 0.7235, 0.6598, 0.7456, 0.3544, 0.1044, 0.6884],
        [0.4628, 0.4325, 0.8167, 0.6705, 0.1071, 0.3300, 0.3518],
        [0.8292, 0.1962, 0.4841, 0.2120, 0.8911, 0.1810, 0.4962],
        [0.0632, 0.5029, 0.6874, 0.6179, 0.7512, 0.8273, 0.6675],
        [0.7667, 0.0182, 0.0058, 0.1733, 0.2128, 0.5805, 0.6621]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor2 = torch.rand(1, 7)
print(tensor2)
# Perform matrix multiplication
tensor3 = torch.matmul(tensor, tensor2.T)
print(tensor3)

tensor([[0.7533, 0.0840, 0.2410, 0.1055, 0.5852, 0.6854, 0.5146]])
tensor([[0.8620],
        [1.4709],
        [1.4626],
        [1.1224],
        [1.6811],
        [1.6709],
        [1.4619]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
seed = torch.manual_seed(0)

# Create two random tensors
tensor4 = torch.rand(7, 7)
tensor5 = torch.rand(1, 7)

# Matrix multiply tensors
tensor6 = torch.matmul(tensor4, tensor5.T)
print(tensor6)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor7 = torch.rand(2, 3).to(device)
tensor8 = torch.rand(2, 3).to(device)
print(tensor7)
print(tensor8)


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
tensor9 = torch.matmul(tensor7, tensor8.T)
print(tensor9)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
tensor10 = torch.max(tensor9)
print(tensor10)
# Find min
tensor11 = torch.min(tensor9)
print(tensor11)


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
max_arg = torch.argmax(tensor9)
print(max_arg)

# Find arg min
min_arg = torch.argmin(tensor9)
print(min_arg)


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor12 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor13 = tensor12.squeeze()

# Print out tensors and their shapes
print(tensor12, tensor12.shape)
print(tensor13, tensor13.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
